spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    zookeeper:
      connect-string: 192.168.29.130:2181
server:
  port: 8004


mybatis:
  type-aliases-package: com.hjy.springcloud.entites
  mapper-locations: classpath:mapper/*.xml