server:
  port: 8006

spring:
  application:
    name: cloud-providerconsul-payment
  cloud:
    consul:
      hostname: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true