server:
  port: 80

spring:
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
      port: 8500
      hostname: localhost
  application:
    name: cloud-consumerconsul-order